/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conclua;

/**
 *
 * @author Rael Flores
 */
public class Cadastro_de_Aluno extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro_de_Aluno
     */
    public Cadastro_de_Aluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botao_fechar_login = new javax.swing.JButton();
        botao_fechar_login1 = new javax.swing.JButton();
        nome_professor = new javax.swing.JTextField();
        celular_professor = new javax.swing.JFormattedTextField();
        matricula_professor1 = new javax.swing.JFormattedTextField();
        matricula_professor2 = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1080, 720));
        setSize(new java.awt.Dimension(1080, 720));
        getContentPane().setLayout(null);

        botao_fechar_login.setBackground(new java.awt.Color(0, 204, 51));
        botao_fechar_login.setFont(new java.awt.Font("Barlow ExtraBold", 0, 14)); // NOI18N
        botao_fechar_login.setForeground(new java.awt.Color(255, 255, 255));
        botao_fechar_login.setText("CADASTRAR");
        botao_fechar_login.setBorder(null);
        botao_fechar_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_fechar_loginActionPerformed(evt);
            }
        });
        getContentPane().add(botao_fechar_login);
        botao_fechar_login.setBounds(320, 600, 240, 30);

        botao_fechar_login1.setBackground(new java.awt.Color(255, 0, 0));
        botao_fechar_login1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        botao_fechar_login1.setForeground(new java.awt.Color(255, 255, 255));
        botao_fechar_login1.setText("X");
        botao_fechar_login1.setBorder(null);
        botao_fechar_login1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_fechar_login1ActionPerformed(evt);
            }
        });
        getContentPane().add(botao_fechar_login1);
        botao_fechar_login1.setBounds(1040, 0, 40, 30);

        nome_professor.setFont(new java.awt.Font("Barlow Medium", 0, 18)); // NOI18N
        nome_professor.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        nome_professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome_professorActionPerformed(evt);
            }
        });
        getContentPane().add(nome_professor);
        nome_professor.setBounds(320, 110, 500, 40);

        try {
            celular_professor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(celular_professor);
        celular_professor.setBounds(320, 350, 220, 40);

        try {
            matricula_professor1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(matricula_professor1);
        matricula_professor1.setBounds(320, 190, 220, 40);

        try {
            matricula_professor2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(matricula_professor2);
        matricula_professor2.setBounds(320, 270, 500, 40);

        jLabel13.setFont(new java.awt.Font("Barlow ExtraBold", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Celular:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(320, 320, 100, 22);

        jLabel10.setFont(new java.awt.Font("Barlow ExtraBold", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Email:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(320, 240, 100, 22);

        jLabel12.setFont(new java.awt.Font("Barlow ExtraBold", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Matricula:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(320, 160, 100, 22);

        jLabel6.setFont(new java.awt.Font("Barlow ExtraBold", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nome:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(320, 80, 70, 22);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tela_cadastro.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1080, 720);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botao_fechar_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_fechar_loginActionPerformed

    }//GEN-LAST:event_botao_fechar_loginActionPerformed

    private void botao_fechar_login1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_fechar_login1ActionPerformed
        dispose();  // TODO add your handling code here:
    }//GEN-LAST:event_botao_fechar_login1ActionPerformed

    private void nome_professorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome_professorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome_professorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro_de_Aluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro_de_Aluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro_de_Aluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro_de_Aluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro_de_Aluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_fechar_login;
    private javax.swing.JButton botao_fechar_login1;
    private javax.swing.JFormattedTextField celular_professor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JFormattedTextField matricula_professor1;
    private javax.swing.JFormattedTextField matricula_professor2;
    private javax.swing.JTextField nome_professor;
    // End of variables declaration//GEN-END:variables
}
